# Site settings
title: Zenity Labs
email: support@zenitylabs.com
url: https://zenitylabs.com
description: "Zenity Labs is a software studio dedicated to building simple products that get out of your way."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Zenity Labs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/zenitylabs
  - title: facebook
    url: https://facebook.com/zenitylabs
  - title: github
    url: https://github.com/zenitylabs

# Build settings
markdown: kramdown
permalink: pretty
