# Site settings
title: Zenity Labs
email: hello@zenitylabs.com
url: https://zenitylabs.com
description: "Zenity Labs is an ideas incubator for creators building software and SaaS businesses"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#1359c8'
  brand: '#1359c8'

# Footer settings
footer: Zenity Labs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/zenitylabs
  - title: facebook
    url: https://facebook.com/zenitylabs
  - title: github
    url: https://github.com/zenitylabs

# Build settings
markdown: kramdown
permalink: pretty
